FROM node:16-alpine

# Let WatchTower know to ignore this container for checking
LABEL com.centurylinklabs.watchtower.enable="false"

WORKDIR /app

COPY ./package*.json ./

RUN yarn

ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /app/dev

COPY . .

CMD ["yarn", "start:dev"]
